### ISSUE TITLE
Tillägg under Diversity

### ISSUE THREAD

**Issue by FredrikRichtner** [guardian-framework/framework#10]
Defining Diversity
Mångfald handlar om att ta tillvara möjligheter och undanröja hinder – att vi på alla plan och nivåer – tar tillvara på olika kompetenser, erfarenheter och talanger. Riksidrottsförbundet står bakom regeringens och riksdagens övergripande mål om allas lika rättigheter, skyldigheter och möjligheter för alla oavsett bakgrund.

Further Reading:
http://www.rf.se/Mangfald/

**Comment by larsbarkman** [comment]
Har du något lika bra på engelska? :-)

**Comment by FredrikRichtner** [comment]
Efter "Google translate" och lite manuell redigering:

Diversity is about to seize opportunities and overcome obstacles, take advantage of different skills, experiences and talents, equal rights, obligations and opportunities for all, regardless of background.

**Comment by larsbarkman** [comment]
Grymt! Jag lägger in det...

Kommer med i nästa Pull Request

**Comment by larsbarkman** [comment]
Pull Request har gått iväg
