### ISSUE TITLE
Ny film Autonomy, Mastery And Purpose

### ISSUE THREAD

**Issue by AndJoh123** [guardian-framework/framework#12]
https://www.youtube.com/watch?v=wdzHgN7_Hs8

**Comment by larsbarkman** [comment]
Gillade de andra bättre. https://github.com/guardian-framework/framework/issues/15

**Comment by ChrickeR** [comment]
Innehållsmässigt var de ju ganska lika men kan hålla med om att jag gillar trilogin bättre, var lite lungnare

**Comment by AndersHaglund** [comment]
Helt OK för mig.
