### ISSUE TITLE
Ny text collaboration

### ISSUE THREAD

**Issue by AndJoh123** [guardian-framework/framework#13]
There’s an app for that." This is no longer just an advertising tagline, it’s the truth.

We live in a connected world—there are apps today that help solve problems you didn’t even know you had and anticipate needs before you realize them. When you can constantly be connected to the Internet, it opens the door for technology solutions to every challenge.

Power in Collaboration

One way of overcoming current challenges is through collaboration—in unexpected ways—with other companies. Today’s fast-paced marketplace requires mutually beneficial partnerships to leverage creativity, experience and resources, with right- and left-brain thinkers, that can help you arrive at a solution in less time.

It’s the classic buy or build question but in overdrive, collaborating to find a better and more efficient way to achieve your goal—because after all, speed is king in highly competitive markets.

By looking for partnerships and collaborating externally, companies are able to innovate much more quickly and even create solutions to problems that may not be prevalent issues yet.

For example, look at streaming video services. According to a study by ABI Research, the market for these services is growing rapidly and is expected to hit $20 billion by 2015. As the market for these services continue to grow, the providers face the challenge of developing services that are more social in nature. This is something that no provider has achieved, but perhaps if they looked externally, one could argue that they would find opportunities to collaborate with other developers and/or start-ups—or even academia—to arrive at solutions much quicker.

While cooperating with other companies in your own industry may seem counterintuitive to competitiveness—the simple fact is it’s not. At Verizon, we are committed to the concept of "co-opetition." For example, Verizon is collaborating with content providers and software developers to provide live TV and video-on-demand content both inside and away from home to FiOS TV customers. Through these partnerships, we have developed the FiOS Mobile app which delivers a simple, seamless way for our customers to watch their favorite programming and content wherever they are, whenever they want. We have also started engaging with developers and start-ups through "meet-ups" in select cities, aimed at creating an environment that showcases the newest innovations to solve the challenges facing today’s connected home.

Collaboration is no longer just a strategy: it is the key to long-term business success and competitiveness. Businesses that realize this sooner rather than later will be the ones who win the game and succeed in the new global economy.

—Bob Mudge is President of Consumer and Mass Business at Verizon

**Comment by AndJoh123** [comment]
länk till text
https://www.fastcompany.com/3024246/leadership-now/why-collaboration-is-crucial-to-success

**Comment by larsbarkman** [comment]
Bra! Skulle den kunna vara vår motivering till Collaboration?

**Comment by AndJoh123** [comment]
Ja det låter bra!

**Comment by larsbarkman** [comment]
Går med i nästa uppdatering
