### ISSUE TITLE
Nya filmer AUTONOMY, MASTERY AND PURPOSE

### ISSUE THREAD

**Issue by AndJoh123** [guardian-framework/framework#15]
https://www.youtube.com/watch?v=nnc1hmZLwOY&list=PLS3JvF3eTLqUVKE-BVmB0iaqFeMpSGEZ1&index=1

https://www.youtube.com/watch?v=wNqOJnA5Ysw&list=PLS3JvF3eTLqUVKE-BVmB0iaqFeMpSGEZ1&index=2

https://www.youtube.com/watch?v=lkipSYV6uJ8&index=3&list=PLS3JvF3eTLqUVKE-BVmB0iaqFeMpSGEZ1

**Comment by AndJoh123** [comment]
Filmerna:
1. Autonomy
2. Mastery
3. Purpose

**Comment by larsbarkman** [comment]
Jättebra!!

Tycker vi kör dom istället för den andra.

**Comment by larsbarkman** [comment]
Lägger till dom i nästa uppdatering.
