### ISSUE TITLE
Ny film trust and guidance

### ISSUE THREAD

**Issue by AndJoh123** [guardian-framework/framework#16]
https://www.youtube.com/watch?v=lmyZMtPVodo

**Comment by AndJoh123** [comment]
Vill att den ersätter den befintliga.

**Comment by larsbarkman** [comment]
Det var en bra film men jag tycker inte att det är en ersättare... Den första filmen adresserar guidance väldigt bra men den andra filmen adresserar trust bra.

Vi borde kanske ha båda?!

**Comment by AndersHaglund** [comment]
Point taken. Ja låt oss ha bägge två.

**Comment by larsbarkman** [comment]
Går med i nästa uppdatering
