### ISSUE TITLE
Ändra på "Pursue Mastery"?

### ISSUE THREAD

**Issue by larsbarkman** [guardian-framework/framework#17]
Är kanske "Personal Mastery" bättre?

Personal mastery is about approaching life from a different perspective. Sometimes people would refer to it as a journey towards continuous improvement. Personal mastery is guided with key principles like vision, personal purpose, creative tension, commitment to truth and understanding the subconscious mind.
[What Is Personal Mastery?](http://hubpages.com/business/what-is-personal-mastery-2)

**Comment by ChrickeR** [comment]
Det är ju ett bra budskap, tycker den känns bra den är lite mjukare.

**Comment by larsbarkman** [comment]
Eller så skulle det kunna vara "Smart Creative"

## So what is a smart creative?

According to Google, these people are the key to success in the Internet Century. Google describes them as someone who combines “business savvy, technical knowledge, creative energy and a hands-on approach to getting things done.”
Someone who:
Is not confined to a specific task, and has access to all of the company’s information and computing power, who is not adverse to taking risks, and is not punished when failure happens.
Is not restricted by organizational structure or role definitions and who is encouraged to exercise their own ideas.
Doesn’t keep quiet when they disagree, get bored easily and shift jobs a lot.
Is multi-dimensional, in that they combine technical depth with business savvy and creative flair.

## Key qualities of the smart creative
- Experts in doing; they design and build, are able to analyze and conceptualize & use data rigorously to make informed business decisions.
- Business smart; they see and practice the lines of sight between technical expertise, product excellence,and business success.
- Competitive smart; they are driven by their own sense of passionate purpose and desire to create ‘great’ things.
- User smart; they understand the end product from the user’s perspective and act an ‘obsessive user’ in their own right.
- Generates creative ideas & is curiously creative; that are genuinely new, are open to multiple perspectives and plays the perspective chameleon when required. Always questioning, debating and seeking problems to solve in their individualistic way.
- Risky, collaborative and takes the initiative and is a good and open communicator.

http://innovationexcellence.com/blog/2016/05/23/the-rise-of-the-smart-creative-lessons-from-google/

**Comment by larsbarkman** [comment]
Caroline gav oss feedback att hon gärna behåller "Technological Mastery" för att betona vikten av att digitaliseringen till stora delar handlar om att bemästra teknologierna som finns nu och de som i allt snabbare takt kommer ut på marknaden.
