### ISSUE TITLE
Ny film kring "passion"

### ISSUE THREAD

**Issue by AndJoh123** [guardian-framework/framework#18]
Vi delar åsikten att empati ska bytas ut till passion. Till det vill vi lägga upp denna film under rubriken defining.

https://www.youtube.com/watch?v=D1R-jKKp3NA

**Comment by larsbarkman** [comment]
Den kör vi på tycker jag!

"Stay hungry. Stay foolish." :-)

**Comment by larsbarkman** [comment]
Går med i nästa uppdatering
