### ISSUE TITLE
Byt plats på text om Defining Trust And Guidance

### ISSUE THREAD

**Issue by AndJoh123** [guardian-framework/framework#19]
Texten under defining är mer en beskrivning om varför och bör därför ligga under rubriken Justification Of The Choices Made. Vi letar ny text till defining.

**Comment by larsbarkman** [comment]
Vad säger ni om att lägga ner texten som ni föreslår och sen lägga till den nya trustfilmen för att definiera Trust och sen flytta ner nuvarande film för att definiera Guidance?

**Comment by larsbarkman** [comment]
Implementeras i nästa uppdatering

**Comment by AndJoh123** [comment]
Ok
