### ISSUE TITLE
Work smarter, not harder

### ISSUE THREAD

**Issue by Roxenborn** [guardian-framework/framework#2]
# Work Smarter, Not Harder

> Performance of the steps comprising a work in a manner that is least expensive (in terms of effort, money, and time) and consistent with the objective of the work.

[http://www.businessdictionary.com/definition/work-simplification.html] 

> För att öka effektiviteten…ska vi inte öka stressen utan snarare hitta bra metoder och använda arbetstiden smartare…. en stor del av arbetsdagen går åt till annat än att åtgärda eller skapa det kunden beställt.

 [http://www.starkearvid.se/Effektivitet.aspx]

**Comment by larsbarkman** [comment]
# Är "rubriken" (Work Smarter, not harder) fel?!

Är det egentligen inte mer Efficiency vs. Effectiveness som vi är ute efter, dvs. att vi ska göra rätt saker inte bara saker på rätt sätt?

Jag föreslår ett byte av titel till "Effectiveness not Efficiency".

Jag vet att vi har pratat om att undvika negativa kommentarer men i detta fall (likt "Products not Projects") tycker jag faktikskt att det tillför något viktigt.

Vad tycker ni @ChrickeR @Roxenborn ?

[Efficiency vs. Effectiveness: What’s the Difference?](http://writingexplained.org/efficiency-vs-effectiveness-difference)
[Effective vs. Efficient](http://www.diffen.com/difference/Effectiveness_vs_Efficiency)
[The Difference Between Effectiveness And Efficiency Explained](http://www.insightsquared.com/2013/08/effectiveness-vs-efficiency-whats-the-difference/)

**Comment by Roxenborn** [comment]
Jag pratade med Elinor om detta förra veckan just i syftet att hitta en synonym. Bra tycker jag.

**Comment by ChrickeR** [comment]
I det här fallet så tycker jag att "Effectiveness not Efficiency" är ett bättre förslag men tror att vi kan hitta något ännu mer passande.

Slänger in en tanketråd som jag hade igår...
Desired value and perceived value. Desired value refers to what customers desire in a product or service. Perceived value is the benefit that a customer believes he or she received from a product after it was purchased.

As Steve Jobs once said: “You can't just ask customers what they want and then try to give that to them. By the time you get it built, they'll want something new.”

http://timreview.ca/article/525

**Comment by ChrickeR** [comment]
Så varför inte gå åt mot "innovation!" hållet den saknas lite i matrisen.

**Comment by ChrickeR** [comment]
Föreslår följande ändring av Change kolumnen

P: Continious improvements

> However, delivering customer value is not a one-off event. Firms must continuously strive to better understand and anticipate what their customers will value and then keep delivering it. As Steve Jobs once said: “You can't just ask customers what they want and then try to give that to them. By the time you get it built, they'll want something new.”
> [(http://timreview.ca/article/525)]

S:  Observe, Orient, Decide and Act
O: Time to Customer Value 
T: Metrics driven deleopment

**Comment by larsbarkman** [comment]
Vad säger du om följande?

P: Outside In
S: Continuous Improvement
O: Metrics driven
T: Time to Customer Value

**Comment by Roxenborn** [comment]
Spot on säger jag

**Comment by larsbarkman** [comment]
Pull Request har gått iväg
