### ISSUE TITLE
Guardian är Alpha 0.0.1

### ISSUE THREAD

**Issue by larsbarkman** [guardian-framework/framework#20]
Efter feedback från Caroline så gjorde vi några ändringar i matrisen som jag tycker blev mycket bra och det är nu ett bättre flyt både våg- och lodrätt.

En väldigt visuell skillnad mot de bilder vi hade i diskussionen är att Principer, Mönster och Standarder ligger kvar i menyn men har lyfts upp en nivå.

Vidare de flesta av de existerande Issues blivit implementerade och finns nu att beskåda.

Feedback uppskattas!

**Comment by ChrickeR** [comment]
Merged
