### ISSUE TITLE
Customer value

### ISSUE THREAD

**Issue by Roxenborn** [guardian-framework/framework#3]
# Kundvärde

**Vi skapar ett kundvärde när vi erbjuder en produkt som är billig för oss men som har ett högt värde för kunden**
[http://sho.co/17V1L]
# Customer value

**The essense of creating a value is trading something that is low cost to you for something that is of high value to your cotumer**
[https://youtu.be/9I2baWR-rqg]

**Comment by larsbarkman** [comment]
Jag har lagt till den engelska texten som summary och lagt in videon som förklaring.

Förändringen kommer gå med min nästa Pull Request.

**Comment by Roxenborn** [comment]
Vad hände med det här? Det är inte samma innehåll längre?

**Comment by larsbarkman** [comment]
Efter diskussioner så blev hela kolumnen ändrad och kundvärde bakades ihop med "Time to cusomer value".

**Comment by UllaForsman** [comment]
Men är inte time to customer value bara en del av customer value. Man kan mäta tiden som en del av kundvärdet men det är inte hela kundvärdet. Det finns ju andra aspekter också så som kvalitet, kostnad mm. Kan man ändra tlllbaka?

**Comment by larsbarkman** [comment]
Allt går alltid att ändra tillbaka :-)

Men om kundvärde är något större, omfattas det då inte av "tid till kundvärde"? dvs. vi måste förklara kundvärde för att kunna säga när vi har nått den och då är det tiden dit som är viktigast. Lite som ränta på ränta effekten...
