### ISSUE TITLE
Byta ut Empathy mot Enthusiasm?

### ISSUE THREAD

**Issue by larsbarkman** [guardian-framework/framework#4]
Hej!

Empathy är superviktigt men jag undrar om inte Enthusiasm är ännu viktigare för oss, vad säger ni?

/Lars

**Comment by larsbarkman** [comment]
Eller är det Passion det borde stå?

/Lars

**Comment by larsbarkman** [comment]
Flyttade diskussionen till "Ändra i The Matrix"

**Comment by ChrickeR** [comment]
Jag gillade ju "passion" 😀

Skickat från min mobil

On Tue, Sep 20, 2016 at 5:00 AM +0200, "Lars Barkman" notifications@github.com wrote:

Hej!

Empathy är superviktigt men jag undrar om inte Enthusiasm är ännu viktigare för oss, vad säger ni?

/Lars
