### ISSUE TITLE
Domain model

### ISSUE THREAD

**Issue by Roxenborn** [guardian-framework/framework#6]
Förslag på definition under Domain model
# Definition of Domain model

> Domain Model will have it’s own internal language that represents the important things that are specific to the domains purpose.

[http://culttt.com/2014/11/19/bounded-contexts-context-maps-domain-driven-design/](http://culttt.com/2014/11/19/bounded-contexts-context-maps-domain-driven-design/)

> A domain model is a system of abstractions that describes selected aspects of a sphere of knowledge, influence, or activity (a domain[3]). The model can then be used to solve problems related to that domain. The domain model is a representation of meaningful real-world concepts pertinent to the domain that need to be modeled in software. The concepts include the data involved in the business and rules the business uses in relation to that data.
> 
> A domain model generally uses the vocabulary of the domain so that a representation of the model can be used to communicate with non-technical stakeholders.

[https://en.wikipedia.org/wiki/Domain_model](https://en.wikipedia.org/wiki/Domain_model)

**Comment by larsbarkman** [comment]
Jag har lagt till den nedre texten.

Jag la även till texten (summary) och bilden från http://martinfowler.com/eaaCatalog/domainModel.html

Förändringen kommer gå med min nästa Pull Request.

**Comment by larsbarkman** [comment]
Pull Request har gått iväg
