### ISSUE TITLE
Addition to Respect the bounded context

### ISSUE THREAD

**Issue by flerpo** [guardian-framework/framework#7]
#### Definintion of Bounded Context

> Bounded Context is a central pattern in Domain-Driven Design. It is the focus of DDD's strategic design section which is all about dealing with large models and teams. DDD deals with large models by dividing  them into different Bounded Contexts and being explicit about their interrelationships.
> -**Martin Fowler**
> [Source](http://martinfowler.com/bliki/BoundedContext.html)

**Comment by larsbarkman** [comment]
Jag har lagt till texten och använde den även som summary.

Förändringen kommer gå med min nästa Pull Request.

**Comment by larsbarkman** [comment]
Pull Request har gått iväg
